flake8:
  enabled: true
  config_file: '/.flake8'
rubocop:
  enabled: false
coffeescript:
  enabled: false
haml:
  enabled: false
golint:
  enabled: false
swift:
  enabled: false

fail_on_violations: true